from datetime import datetime

from sqlalchemy import DateTime, Integer, String, Text, func
from sqlalchemy.orm import Mapped, mapped_column

from app.db import Base


class Upload(Base):
    """Store metadata and transcription state for one audio upload"""
    __tablename__ = "uploads"

    id: Mapped[str] = mapped_column(String, primary_key=True) #generated by the app, used to id the stored audio

    filename: Mapped[str] = mapped_column(String, nullable=False)

    storage_key: Mapped[str] = mapped_column(String, nullable=False) # a relative storage key, not the audio bytes themselves

    # New recordings wait in the queue until a worker processes them
    status: Mapped[str] = mapped_column( 
        String,
        default="queued",
        nullable=False,
    )

    # The existing uploads table requires progress on every inserted row.
    progress: Mapped[int] = mapped_column(Integer, default=0, nullable=False)

    transcript: Mapped[str | None] = mapped_column(
        Text,
        nullable=True,
    )

    #Postgres supplies the timestamp when the row is inserted
    created_at: Mapped[datetime] = mapped_column(
        DateTime,
        server_default=func.now(),
        nullable=False,
    )
    summary: Mapped[str | None] = mapped_column(
        Text,
        nullable=True,
    )

    # This column already exists in the shared uploads table.
    error_message: Mapped[str | None] = mapped_column(Text, nullable=True)
